feat(facial-expressions): add the facial expression feature and display them in speakerstats
jitsi/jitsi-meet pull request #10006
Opened 2021-09-23 12:20 UTC by gabiborlea

Adds the facial expression feature. It uses the face-api.js library which is used in a web worker. The web worker receives image data that comes from a canvas created from the local video track. The web worker sends back the expression and then the main thread will send the expression to the other participants via data channel and to the xmpp sever, also saving it to the redux state. Then the expressions from all participants will are shown in the speaker stats dialog.

2021-09-23 12:43 UTC, damencho commented
Nice one!

How often is this beeing sent to the backend?

2021-09-23 12:44 UTC, damencho commented
Maybe we will need a config.js property to disable this functionality

2021-09-23 12:45 UTC, damencho commented
Jenkins add to whitelist.

2021-09-23 12:58 UTC, gabiborlea commented
The detection is done every 1000ms when using webgl and every 3000ms when using cpu, and the last facial expression with its duration is sent to the backend when a new one that is not the same with the last one occurs. 
And if the disableFacialRecognition flag is set to true in the config.js it will be disabled.

2021-09-23 13:04 UTC, damencho commented
> The detection is done every 1000ms when using webgl and every 3000ms when using cpu, and the last facial expression with its duration is sent to the backend when a new one that is not the same with the last one occurs.

In your tests how often the change is triggered?

Hum, but wait how is my expression propagated to the other participants?

And about the config, you haven't documented it in config.js or I missed that, check how we have commented the default value with some simple explanation what it does.

2021-09-23 13:19 UTC, gabiborlea commented
I managed to change the facial expression every second for like 4 or 5 seconds, and the expression was sent to the backend every second, but this would be the worst-case as it is not natural to change your facial expression every second. 
The expression is propagated to the other participants during the conference via the data channel. When the user joins the conference he will receive the facial expressions of the other participant that occurred prior to his join from the prosody.
Sorry, I did not document the flag in config.js.

2021-09-27 07:12 UTC, gabiborlea commented
I forgot to mention that you can test the feature at https://gborlea.jitsi.net/.
If you open the speaker stats dialog it should look like this.
<img width="806" alt="Screenshot 2021-09-27 at 10 10 53" src="https://user-images.githubusercontent.com/57035818/134861195-efe8cd9a-49ff-430b-b8a3-28221f712ffb.png">

2021-11-08 09:07 UTC, quitrk requested changes

2021-11-08 09:37 UTC, gabiborlea commented on react/features/facial-recognition/middleware.js
> +        dispatch(setFacialRecognitionAllowed(true));
I used that flag for preventing the recognition from starting in the prejoin screen

2021-11-08 10:55 UTC, gabiborlea commented on react/features/facial-recognition/actions.js
> +            sendDataToWorker(worker, imageCapture, detectionTimeInterval);
Fixed it.

2021-11-08 10:55 UTC, gabiborlea commented on react/features/facial-recognition/reducer.js
> +        if (action.muted && state.cameraTimeTracker.lastCameraUpdate !== 0) {
Removed it.

2021-11-08 10:55 UTC, gabiborlea commented on react/features/facial-recognition/middleware.js
> +        if (!enableFacialRecognition) {
Fixed it.

2021-11-08 11:15 UTC, quitrk submitted a review, later dismissed

2021-11-08 11:45 UTC, quitrk commented
jenkins please test this please

2021-11-08 12:43 UTC, gabiborlea commented
jenkins please test this please

2021-11-10 08:02 UTC, saghul commented
Jenkins add to whitelist.

2021-11-10 08:03 UTC, saghul commented
Jenkins please test this please.

2021-11-10 09:48 UTC, gabiborlea commented
Jenkins please test this please.

2021-11-15 12:07 UTC, quitrk approved these changes

2021-11-17 14:06 UTC, gabiborlea commented
Jenkins please test this please.

2021-11-17 14:32 UTC, andrei-gavrilescu approved these changes

2021-11-17 14:33 UTC, merged