fix(participants-pane) Place Dominant Speaker first in participants list
jitsi/jitsi-meet pull request #10095
Opened 2021-10-04 12:57 UTC by robertpin

2021-10-04 14:25 UTC, saghul commented on react/features/participants-pane/components/web/MeetingParticipantItems.js
> +    const renderParticipant = id => id && (
This can go away once you skip adding nulls.

2021-10-05 09:01 UTC, saghul requested changes
Left some comments, PTAL. LEt's move this function to the participants-pane feature, since that's where it belongs too. This sorting won't be applied to the filmstrip / tile view, will it?

2021-10-06 12:23 UTC, robertpin commented
> Left some comments, PTAL. LEt's move this function to the participants-pane feature, since that's where it belongs too. This sorting won't be applied to the filmstrip / tile view, will it?

Done.

No, it's just applied to the list in participants pane

2021-10-06 13:09 UTC, saghul approved these changes

2021-10-06 13:11 UTC, merged