feat: (speaker-stats) add speaker stats feature to native
jitsi/jitsi-meet pull request #10349
Opened 2021-11-10 17:54 UTC by andioltean

add speaker stats feature to mobile version of app
used new /native and /web folder structure for SpeakerStats* component
used new JitsiScreen modal

Screenshots
https://user-images.githubusercontent.com/5053543/137898438-14f07c4a-e709-4c0e-8b97-eea8ef9a6a4d.png
https://user-images.githubusercontent.com/5053543/137898446-1262285a-1cc6-40a1-95c5-04550688bf8a.png

2021-11-11 08:38 UTC, quitrk requested changes

2021-11-11 08:38 UTC, quitrk commented on react/features/speaker-stats/components/web/SpeakerStatsButton.js
> +        sendAnalytics(createToolbarEvent('speaker.stats'));
shouldn't we send analytics regardless of `handleClick` being truthy or not?

2021-11-11 08:38 UTC, quitrk commented on react/features/speaker-stats/components/web/SpeakerStatsButton.js
> +        sendAnalytics(createToolbarEvent('speaker.stats'));
i see you're sending it anyway in the `handleClick` so maybe remove it from there and just send it from here

2021-11-11 08:55 UTC, quitrk commented on react/features/speaker-stats/components/web/SpeakerStatsButton.js
> +        sendAnalytics(createToolbarEvent('speaker.stats'));
nvm, i confused things here

2021-11-11 08:56 UTC, quitrk submitted a review, later dismissed

2021-11-16 13:13 UTC, saghul commented
Jenkins add to whitelist.

2021-11-16 13:14 UTC, saghul commented
Jenkins please test this please.

2021-11-25 13:35 UTC, Calinteodor commented on react/features/speaker-stats/components/native/SpeakerStatsItem.js
> +        ? colors.success04 : colors.surface07;
Please use BaseTheme here. More exactly BaseTheme.palette object.

2021-11-25 16:57 UTC, Calinteodor submitted a review, later dismissed

2021-11-25 18:14 UTC, Calinteodor approved these changes

2021-11-25 18:17 UTC, merged