feat: (local-video-recordings) enable users to record their conference locally
jitsi/jitsi-meet pull request #10622
Opened 2021-12-15 09:40 UTC by andioltean

all users can now record the conference locally
it works in the same way other recordings works
when recording is complete a file is created and stored locally

![image](https://user-images.githubusercontent.com/5053543/146162030-344beda8-d1c8-4454-8bf5-ab994b1a1c99.png)

2021-12-16 13:31 UTC, quitrk requested changes
it seems that you're using the same `localRecording' naming for different data types (boolean, string, object) and it's creating a lot of confusion

2021-12-16 13:31 UTC, quitrk commented on react/features/base/participants/functions.js
> +    const { localRecording } = participant.localRecording;
this doesn't look right

2021-12-16 13:31 UTC, quitrk commented on react/features/base/participants/functions.js
> +    const { localRecording } = toState(stateful)['features/base/participants'];
should this be `localRecordingQueue`?

2021-12-16 13:31 UTC, quitrk commented on modules/API/API.js
> +            const localParticipant = getLocalParticipant(APP.store.getState());
shouldn't this take into account recordings already in progress?

2021-12-16 13:31 UTC, quitrk commented on react/features/base/participants/middleware.js
> +        localRecording: newValue
if this is supposed to be a boolean indicating whether this participant is recording or not, it should be reflected in its naming (initially I thought it is holding some object with recording info)

2021-12-16 13:31 UTC, quitrk commented on modules/API/API.js
> +     * @param {string} localRecording - Whether user has raised hand.
why is this a string rather than a boolean? also the naming is confusing

2021-12-16 14:05 UTC, damencho commented
I was wondering, is this different than the local recording we have in https://github.com/jitsi/jitsi-meet/tree/master/react/features/local-recording, or these it reuse something from it?

2021-12-16 14:23 UTC, andioltean commented on react/features/recording/middleware.js
> +            setTimeout(() => {
there's a delay between when the recording is topped and the data is starting to get dumped. I could not find in the docs some event that handled this

2021-12-17 09:10 UTC, andioltean commented
Please jenkins test this please

2021-12-17 11:24 UTC, andioltean commented
this local video recording

2021-12-17 11:25 UTC, andioltean commented
> I was wondering, is this different than the local recording we have in https://github.com/jitsi/jitsi-meet/tree/master/react/features/local-recording, or these it reuse something from it?

this is local video recording

2021-12-17 12:57 UTC, damencho commented
Confusing is that they share the same name ...
Even the config is with same name 
https://github.com/jitsi/jitsi-meet/blob/8e9034601d66947840adb21399559f405a80da49/config.js#L865

2021-12-17 13:09 UTC, andioltean commented
> Confusing is that they share the same name ... Even the config is with same name
> 
> https://github.com/jitsi/jitsi-meet/blob/8e9034601d66947840adb21399559f405a80da49/config.js#L865

that config is for sound recording only. I didn't add a config for local video recordings. Also I was under the impression that sound recording would not be used aby more.

2021-12-17 13:19 UTC, damencho commented
Well that is in the code, and when reading all events for local recording, I think of them as that feature.
Maybe use another name like localVideoRecording

2022-01-11 13:54 UTC, monnier commented
Sounds like just the thing I need, but I have some questions:

- You say "when recording is complete a file is created and stored locally".  Is the (partial) recording stored in the file only at the very end?  What happens if the browser/computer crashes after an hour or two of recording?
- Does this require re-encoding the video, and hence loads the local CPU even more?  If so, can the re-encoding be done offline so it doesn't affect the recording itself?

2022-01-11 14:01 UTC, saghul commented
Recording is performed using the MediaRecorder API: https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder -- It basically behaves as an ongoing download. Video needs to be encoded because what we'll capture is the entire tab.

2022-01-14 10:31 UTC, ei8fdb commented
Just to check - this local video/audio recording feature will be rolled out to meet.jit.si also? Thanks for working on this. I appreciate it.

2022-01-14 10:34 UTC, saghul commented
> Just to check - this local video/audio recording feature will be rolled out to meet.jit.si also? Thanks for working on this. I appreciate it.

Yes it will, once it's ready.

2022-01-15 17:51 UTC, gigabyteservice commented
MediaRecorder will only record our own video, does this PR can record videos of all other participants just like jibri? is it a replacement for the jibri?

2022-01-17 06:27 UTC, saghul commented
Incorrect. MediaRecorder will record the given mediastream. In this case we feed it a steam which records the current tab, which we obtain with getDisplayMedia.

This is not a replacement for Jibri, but an alternative for simpler use cases.

2022-03-04 13:47 UTC, saghul commented
Superseded by https://github.com/jitsi/jitsi-meet/pull/10894

2022-03-04 13:47 UTC, closed without merging