feat(external-api) add commands to open/close the participants pane
jitsi/jitsi-meet pull request #10888
Opened 2022-02-01 10:48 UTC by mihhu

- toggleParticipantsPane
- setParticipantsPane to be used without state management

2022-02-01 12:59 UTC, damencho commented
Can you add tests for this, thank you.

2022-02-02 07:02 UTC, mihhu commented
Please Jenkins test this please!

2022-02-03 10:31 UTC, mihhu commented
Please Jenkins test this please!

2022-02-03 12:07 UTC, mihhu commented
Please Jenkins test this please!

2022-02-03 15:58 UTC, horymury commented
I think we don't need both a toggle and an explicit set of the open state of the participants pane. Also a new action for opening/closing seems redundant.

I would go with only leaving explicit set of open/closed for the pane, and also expose a function which returns the current open state of the pane, so the integrator can know whether he/she should close or open.


@saghul  @damencho  WDYT?

2022-02-03 16:25 UTC, horymury commented
> I'm not sure ... Personally, I have a problem reading setParticipantsPane: enabled ... I would think this enables/disables the participant pane, but in the code, I see it sets the isOpen flag...

It also confused me, but I was mentioning that we don t even need that action at all,. as we already have actions for open/close

2022-02-04 12:00 UTC, horymury submitted a review, later dismissed

2022-02-04 13:32 UTC, horymury requested changes

2022-02-04 13:32 UTC, horymury commented on modules/API/external/external_api.js
> +    getParticipantsPaneVisibility() {
maybe rename to isParticipantsPaneOpen for clarity

2022-02-04 13:49 UTC, horymury approved these changes

2022-02-04 14:11 UTC, merged