refactor(prejoin) use jss instead of sass in DialInDialog
jitsi/jitsi-meet pull request #11122
Opened 2022-03-13 14:32 UTC by c0m1t

Convert Sass to JSS in `DialInDialog` component.

2022-03-14 14:20 UTC, robertpin requested changes

2022-03-14 14:20 UTC, robertpin commented on react/features/prejoin/components/dialogs/DialInDialog.js
> +        root: {
Can you rename it to `dialog`? I think `root` is kinda vague

2022-03-14 14:20 UTC, robertpin commented on react/features/prejoin/components/dialogs/DialInDialog.js
> +        <div className = { clsx('prejoin-dialog-dialin', classes.root) }>
Do we still need the `prejoin-dialog-dialin` class here? Is it used by tests? If not let's remove it please

2022-03-14 14:20 UTC, robertpin commented on react/features/prejoin/components/dialogs/DialInDialog.js
> +        <div className = { clsx('prejoin-dialog-dialin', classes.root) }>
Do we still need the `prejoin-dialog-dialin` class here? Is it used by tests? If not let's remove it please

2022-03-15 11:17 UTC, robertpin approved these changes

2022-03-15 11:17 UTC, robertpin commented
@c0m1t please rebase this

2022-03-15 11:22 UTC, c0m1t commented
@robertpin Done.

2022-03-15 11:23 UTC, robertpin approved these changes

2022-03-15 11:30 UTC, merged