feat(stage) Add stage filmstrip (multiple participants on stage)
jitsi/jitsi-meet pull request #11145
Opened 2022-03-16 11:22 UTC by robertpin

See multiple participants on stage
Pin and unpin to stage
Automatic selection of participants to be displayed on the stage filmstrip based on dominant speaker changes
Make Filmstrip a reusable component. Used by MainFilmstrip (old functionality) and the new StageFilmstrip
Rename DominantSpeakerName to StageParticipantNameLabel
Active border now showed only for the dominant speaker (no longer for the pinned participant)
Hide video from the vertical filmstrip for the participants on stage

2022-03-17 09:05 UTC, robertpin commented
Jenkins test this please

2022-03-17 09:31 UTC, quitrk requested changes

2022-03-17 09:31 UTC, quitrk commented on react/features/filmstrip/actionTypes.js
> +export const ADD_ACTIVE_PARTICIPANT = 'ADD_ACTIVE_PARTICIPANT';
name is a bit misleading imo, maybe something like `ADD_STAGE_PARTICIPANT` along with the name changes for derived functionality..wdyt?

2022-03-17 09:31 UTC, quitrk commented on react/features/filmstrip/functions.web.js
> +    if ((!tileViewActive && isScreenSharing && isRemoteParticipant) || (isActiveParticipant && !tileViewActive)) {
`if (!tileViewActive && ((isScreenSharing && isRemoteParticipant) || isActiveParticipant))`?

2022-03-17 09:31 UTC, quitrk commented on react/features/filmstrip/components/web/ThumbnailWrapper.js
> +        const participantsLenght = stageFilmstrip ? remoteParticipantsLength
typo at `length`

2022-03-17 14:59 UTC, robertpin commented
Jenkins test this please

2022-03-18 07:59 UTC, robertpin commented
Jenkins test this please

2022-03-18 09:02 UTC, robertpin commented
Jenkins test this please

2022-03-18 10:16 UTC, robertpin commented
Jenkins test this please

2022-03-18 11:35 UTC, robertpin commented
Jenkins test this please

2022-03-18 12:02 UTC, robertpin commented
Jenkins test this please

2022-03-21 09:11 UTC, robertpin commented
Jenkins test this please

2022-03-21 10:27 UTC, robertpin commented on react/features/filmstrip/functions.web.js
> +    return !filmstrip?.disableStageFilmstrip && remoteScreenShares.length === 0
I don't think we want it to work with the horizontal filmstrip, but I'll check

2022-03-21 10:28 UTC, robertpin commented on react/features/conference/components/web/Conference.js
> +export const LAYOUT_CLASSNAMES = {
Yes, but implementing it like that is not trivial, so I'd rather do it as a refactor after this is merged

2022-03-21 10:30 UTC, robertpin commented on react/features/base/participants/functions.js
> +        const { activeParticipants } = state['features/filmstrip'];
This function is only called when there's just one (it's called in order to determine the participant on Large Video, which is displayed only when there's just one active participant)

2022-03-21 10:30 UTC, robertpin commented on config.js
> +    //     disableStageFilmstrip: false
I'll ask

2022-03-21 11:07 UTC, robertpin commented
Jenkins test this please

2022-03-21 11:30 UTC, robertpin commented
Jenkins test this please

2022-03-21 12:00 UTC, robertpin commented
Jenkins test this please

2022-03-21 12:31 UTC, robertpin commented
Jenkins test this please

2022-03-22 07:21 UTC, robertpin commented on react/features/filmstrip/functions.web.js
> +    return !filmstrip?.disableStageFilmstrip && remoteScreenShares.length === 0
The answer is no. I'll change the code to make sure the feature is disabled for horizontal filmstrip

2022-03-22 07:22 UTC, robertpin commented on config.js
> +    //     disableStageFilmstrip: false
Yes we do

2022-03-28 07:02 UTC, quitrk requested changes

2022-03-28 08:29 UTC, robertpin commented on react/features/filmstrip/middleware.web.js
> +        if (activeParticipantsIds.find(pId => pId === id)) {
No, but we want the PARTICIPANT_LEFT to go through. The only thing we care about here is that if a stage participant leaves we clear the slot

2022-03-28 11:16 UTC, quitrk commented on react/features/filmstrip/middleware.web.js
> +        if (activeParticipantsIds.find(pId => pId === id)) {
what I meant was, don't we just skip the check and always call remove?

2022-03-29 08:45 UTC, merged

2022-04-14 14:41 UTC, hristoterezov commented on react/features/filmstrip/components/web/StageFilmstrip.js
> +const StageFilmstrip = (props: Props) => props._currentLayout === LAYOUTS.VERTICAL_FILMSTRIP_VIEW && (
Shouldn't we check for stage filmstrip view here?