refactor(virtual-background): use jss instead of sass
jitsi/jitsi-meet pull request #11152
Opened 2022-03-16 14:42 UTC by c0m1t

Convert Sass to JSS in `virtual-background` feature.

2022-03-22 08:25 UTC, robertpin requested changes

2022-03-22 08:25 UTC, robertpin commented on react/features/virtual-background/components/VirtualBackgroundDialog.js
> +                padding: '0 10px'
Please reuse styles. Create a class that contains all the common styles for blur classes and use that

2022-03-22 08:25 UTC, robertpin commented on react/features/virtual-background/components/UploadImageButton.js
> +            marginRight: theme.spacing(2)
Please add `px` unit

2022-03-29 08:52 UTC, robertpin commented
@c0m1t I don't see any changes. Forgot to push?

2022-03-29 08:54 UTC, c0m1t commented
@robertpin Oh yes I pushed it.

2022-03-29 09:07 UTC, robertpin approved these changes

2022-03-29 09:07 UTC, merged