fix(chat-scroll) Fix scrolling chat in safari
jitsi/jitsi-meet pull request #11734
Opened 2022-06-23 15:52 UTC by apetrus20

Added a fix for when there are more messages in the chat than a screen could display on safari.

2022-06-23 17:43 UTC, saghul requested changes

2022-06-24 07:31 UTC, apetrus20 commented on package.json
> +    "seamless-scroll-polyfill": "^2.1.8",
I updated the dependency with an exact version.

2022-06-24 09:28 UTC, saghul commented
Jenkins please test this please.

2022-06-24 12:23 UTC, horymury approved these changes

2022-06-24 20:19 UTC, saghul approved these changes

2022-06-24 20:19 UTC, merged