feat(ui-components) Add Checkbox component
jitsi/jitsi-meet pull request #11927
Opened 2022-07-29 09:19 UTC by robertpin

Replace all checkboxes in the Settings Dialog
Convert some dialog tabs to TS

2022-07-29 10:59 UTC, saghul commented
Is the AtlasKit checkbox used anywhere else now?

2022-07-29 11:13 UTC, robertpin commented
> Is the AtlasKit checkbox used anywhere else now?

Not sure, but I plan on replacing all in future PRs

2022-08-02 07:42 UTC, saghul requested changes

2022-08-02 08:19 UTC, robertpin commented on react/features/base/ui/components/web/Checkbox.tsx
> +                src = { indeterminate ? IconHorizontalLine : IconCheckMark } />
Yes,  indeterminate is needed for Checkbox Group. I forgot to remove it

2022-08-02 08:44 UTC, saghul commented
Can we drop `IconHorizontalLine` then?

2022-08-02 10:49 UTC, saghul approved these changes

2022-08-02 10:51 UTC, merged