lang: Update Chinese translation
jitsi/jitsi-meet pull request #12104
Opened 2022-09-01 02:15 UTC by thttg

- Remove mistranslations & machine translations
- Update Chinese translation to the latest version
- Remove Thai & make minor changes for clarification in language list

2022-09-07 06:05 UTC, saghul commented
Please drop the changes unrelated to the Chinese translation, we can't merge the PR like that and some of them require discussion.

We will not be renaming English to English (US) for example.

2022-09-07 06:48 UTC, thttg commented
> Please drop the changes unrelated to the Chinese translation, we can't merge the PR like that and some of them require discussion.
> 
> We will not be renaming English to English (US) for example.

I restored these changes and only keep "Canadian" to "Canada".

2022-09-07 07:18 UTC, saghul approved these changes

2022-09-13 09:26 UTC, thttg commented
The conflicts have been resolved.

2022-09-16 18:18 UTC, thttg commented
@saghul Would you mind reviewing it again? The previous one was dismissed because I had to resolve the conflicts.

2022-09-26 22:52 UTC, thttg commented
Hi @damencho would you mind reviewing this PR?

2022-09-27 12:25 UTC, damencho commented
Jenkins test this please.

2022-09-27 13:55 UTC, damencho requested changes

2022-09-27 17:36 UTC, thttg commented on lang/languages.json
> +    "frCA": "French (Canada)",
I dropped it.

2022-09-27 17:44 UTC, damencho approved these changes

2022-09-27 17:44 UTC, merged