ref(ui-components) Update some dialogs to use the new component
jitsi/jitsi-meet pull request #12288
Opened 2022-10-03 10:19 UTC by robertpin

Improve Dialog component to auto close on cancel or on submit
Change logic to determine whether a dialog is using the new component
Convert some files to TS

2022-10-03 10:20 UTC, robertpin commented
The logic to determine whether a component is using the new dialog component is necessary because some imports broke the webpack build

2022-10-03 10:44 UTC, robertpin commented
Jenkins test this please

2022-10-04 08:07 UTC, horymury requested changes

2022-10-04 08:07 UTC, horymury commented on react/features/base/dialog/middleware.web.ts
> +    const list = [ KeyboardShortcutsDialog, ChatPrivacyDialog, DisplayNamePrompt, EmbedMeetingDialog ];
the list can be a constant outside the func.

2022-10-04 08:58 UTC, horymury approved these changes

2022-10-04 08:58 UTC, horymury approved these changes

2022-10-04 09:44 UTC, merged