Remove poll voter name from poll data
jitsi/jitsi-meet pull request #12308
Opened 2022-10-05 09:34 UTC by apetrus20

2022-10-06 12:24 UTC, saghul requested changes
Please take a look at the linter errors.

2022-10-06 12:24 UTC, saghul commented on react/features/polls/components/AbstractPollAnswer.tsx
> +    const participantName = getParticipantDisplayName(reduxState, poll.senderId);
Pl write this as a selector, not using that auxiliary reduxState

2022-10-06 12:24 UTC, saghul commented on react/features/polls/middleware.ts
> +            (_: any, data: any) => {
PL rename the parameter instead of using _

2022-10-06 12:24 UTC, saghul commented on react/features/polls/middleware.ts
> +            (_: any, data: any) => {
ditto

2022-10-25 14:53 UTC, saghul reviewed
LGTM, though I haven't tested it yet. Does the mobile part need an update?

2022-10-25 14:53 UTC, saghul commented on react/features/polls/components/AbstractPollAnswer.tsx
> +import { getParticipantDisplayName } from '../../base/participants';
import this from /functions and you can remove the ts-ignore.

2022-10-25 19:57 UTC, saghul commented
Update: tested and working nicely, good job! Please check mobile needs no changes and address the nit so ts-ignore is not needed and we're good to go!

2022-11-01 19:01 UTC, saghul commented
What the status of this?

2022-11-02 15:25 UTC, apetrus20 commented
> What the status of this?

I made all the changes and I tested it on mobile as well, it's working nicely on mobile as well.

2022-11-03 12:36 UTC, saghul requested changes

2022-11-03 12:36 UTC, saghul commented on react/features/polls/reducer.ts
> +                    voters: typeof voters?.length === 'number' ? [ ...voters ] : { ...voters }
Can't we normalize this at this level? That is, if we get an object / map transfor it into an array?

Also, I feel like this needs a comment to make sure what's happening is properly understood.

2022-11-03 12:36 UTC, saghul commented on react/features/polls/reducer.ts
> +            if (typeof voters?.length === 'number') {
Yeah all this looks odd. Let's convert the old format to the new one and then only process that please.

2022-11-03 14:12 UTC, saghul commented on react/features/polls/reducer.ts
> +                const answerVoters = _answer.voters
Can you pl add a comment here that explains you are supporting the old data model?

2022-11-03 14:22 UTC, saghul approved these changes

2022-11-03 15:08 UTC, merged