show picture-in-picture button while share screen
jitsi/jitsi-meet pull request #12516
Opened 2022-11-04 19:56 UTC by iospro

show picture-in-picture button while share screen to allow compact JitsiMeetView
(significant when SDK is embedded in some host app)

2022-11-04 21:07 UTC, saghul commented
We don't want to allow that. I think an extra flag would be acceptable.

2022-11-05 01:06 UTC, iospro commented
And what is the reason now to hide this while translation?

2022-11-08 08:29 UTC, saghul commented on react/features/base/flags/constants.ts
> + * Flag indicating if Picture-in-Picture button should be shown while translation.
This description sounds very confusing. There is nothing related to translations here. What you want is to enable it while screen sharing.

2022-11-08 14:20 UTC, saghul requested changes

2022-11-08 14:20 UTC, saghul commented on react/features/base/flags/constants.ts
> +export const PIP_AT_SCREEN_SHARING_ENABLED = 'pip-at-screen-sharing.enabled';
Please call this PIP_WHILE_SCREEN_SHARING_ENABLED

2022-11-08 15:23 UTC, saghul approved these changes

2022-11-08 15:25 UTC, merged