feat(face-landmarks): add face landmarks timeline
jitsi/jitsi-meet pull request #12561
Opened 2022-11-15 12:46 UTC by gabiborlea

can be tested at: https://gborlea.jitsi.net/
<img width="669" alt="Screenshot 2022-11-15 at 14 45 40" src="https://user-images.githubusercontent.com/57035818/201922946-63903c94-2995-4718-95ff-10aefe58e08f.png">

2022-11-21 10:48 UTC, horymury requested changes

2022-11-21 10:48 UTC, horymury commented on react/features/speaker-stats/reducer.ts
> +    case SET_OFFSET: {
think this action is not used. as the corresponding action is not used and no middleware process it.

2022-11-21 11:00 UTC, horymury commented on react/features/speaker-stats/components/AbstractSpeakerStatsList.ts
> +        return () => {
think you clear the interval both on mount and unmount.

2022-11-21 11:08 UTC, horymury commented on react/features/speaker-stats/components/web/SpeakerStats.tsx
> +                            <Tooltip
nit:

maybe do an object array and do a map on it, something like:

``` 
const STATS_LEGEND = [
   {
       translationKey: 'speakerStats.neutral',
       icon:  IconEmotionsNeutral
    },
   {
       translationKey: 'speakerStats.happy',
       icon:  IconEmotionsHappy
    },
....
]
...... 
{STATS_LEGEND.map(stat => (
                               <Tooltip
                                    content = { t(stat.translationKey) }
                                    position = { 'top' }
                                    key = {some_key}>
                                    <Icon
                                        size = { 20 }
                                        src = { stat.icon} />
                            </Tooltip>
)}

2022-11-21 13:02 UTC, dudumanbogdan commented on react/features/speaker-stats/functions.ts
> +    return startTimestamp ? Date.now() - startTimestamp : undefined;
should be `null` instead of `undefined` as it's an intentional absence of the value

2022-11-21 13:05 UTC, dudumanbogdan commented on react/features/speaker-stats/functions.ts
> + * @param {ISpeakerStats | undefined} stats - The unfiltered stats.
is this really returning as well `undefined`? eg: when no criteria and stats, it's returning default value from `getSpeakerStats` which is empty object

2022-11-21 13:06 UTC, dudumanbogdan commented on react/features/speaker-stats/functions.ts
> + * @param {ISpeakerStats | undefined} stats - The unfiltered stats.
same as above, undefined?

2022-11-21 13:07 UTC, dudumanbogdan commented on react/features/speaker-stats/middleware.ts
> +        if (Math.abs((right + action.value) - currentDuration) < 1000) {
will be nice to move to const this 1000 ms (eg: DEFAULT_REFRESH_TIME or something more to business oriented)

2022-11-21 13:56 UTC, gabiborlea commented on react/features/face-landmarks/FaceLandmarksHelper.ts
>          if (detections[0].emotion) {
a better candidate would be const detection = detections[0], as we check if we have only one detection

2022-11-21 15:16 UTC, gabiborlea commented on react/features/speaker-stats/components/web/Timeline.tsx
> +    const handleOnMouseMove = (event: MouseEvent) => {
tried with debounce, for panning purposes does not work well

2022-11-21 15:25 UTC, gabiborlea commented on react/features/face-landmarks/types.ts
> +export type FaceLandmarks = {
I used typescript types until this point, if this is the case I can change all to interfaces

2022-11-21 15:26 UTC, gabiborlea commented on react/features/face-landmarks/types.ts
> +export type FaceLandmarks = {
I prefer using types as I see that interfaces have the I prefix

2022-11-22 08:42 UTC, dudumanbogdan requested changes

2022-11-22 08:42 UTC, dudumanbogdan commented on react/features/speaker-stats/components/web/Timeline.tsx
> +                        area-label = { faceExpression }
This is still showing with `area-label`

2022-11-22 08:42 UTC, dudumanbogdan commented on react/features/speaker-stats/components/web/SpeakerStatsItem.tsx
> +    t: Function;
no need changes: i observed that now we can skip this manual step of adding a prop for translation by using interface and `interface A extends WithTranslation` and t will be available in the `:Props`

2022-11-22 08:43 UTC, dudumanbogdan requested changes

2022-11-22 08:43 UTC, dudumanbogdan commented on react/features/speaker-stats/components/web/Timeline.tsx
> +                    area-label = 'end'
This is still showing with area-label

2022-11-22 09:43 UTC, horymury commented on react/features/speaker-stats/components/web/Timeline.tsx
> +    const handleOnMouseMove = (event: MouseEvent) => {
have you tried the debounce in tandem with useCallback/useMemo?

2022-11-22 12:26 UTC, horymury commented on react/features/speaker-stats/components/web/Timeline.tsx
> +    const handleOnMouseMove = (event: MouseEvent) => {
we tried debounce and it breaks the smootness of panning.

2022-11-22 12:33 UTC, dudumanbogdan approved these changes
looks good to me 👍

2022-11-22 12:35 UTC, horymury approved these changes

2022-11-22 13:56 UTC, merged