task(rn) removes webviews and opens urls in browser
jitsi/jitsi-meet pull request #12686
Opened 2022-12-14 13:58 UTC by tmoldovan8x8

2022-12-15 08:36 UTC, saghul requested changes

2022-12-15 08:36 UTC, saghul commented on react/features/settings/components/native/SettingsView.tsx
> +import { Button, Divider } from 'react-native-paper';
Make it tertiary, IIRC they show as a link (visually)

2022-12-16 10:19 UTC, Calinteodor commented on react/features/settings/components/native/SettingsView.tsx
> +import { Button, Divider } from 'react-native-paper';
![image](https://user-images.githubusercontent.com/26413496/208076744-5e21e290-3f6d-4026-bbfe-b22bbffdbd65.png)

The links don't have the blue token color, but INMHO, I think they look better now. WDYT @saghul ?

2022-12-16 10:20 UTC, Calinteodor commented on react/features/settings/components/native/SettingsView.tsx
> +import { Button, Divider } from 'react-native-paper';
Aside from that, everything works and feels as expected.

2022-12-16 10:27 UTC, saghul commented on react/features/settings/components/native/SettingsView.tsx
> +import { Button, Divider } from 'react-native-paper';
LGTM, they are tertiary buttons and that's the design we got for them :-)

2022-12-16 10:30 UTC, Calinteodor approved these changes

2022-12-16 12:30 UTC, saghul approved these changes

2022-12-16 12:30 UTC, merged