Fixed overflow of popover
jitsi/jitsi-meet pull request #12814
Opened 2023-01-22 21:21 UTC by hkirat

Closes https://github.com/jitsi/jitsi-meet/issues/12739

This happens on smaller machines, the fix/hack I've added is to restrict the height of the popover and add scroll to it.

2023-01-23 10:00 UTC, saghul commented
@robertpin Can you please review this?

2023-01-25 11:31 UTC, robertpin commented
Please fix the lint errors

2023-01-25 11:34 UTC, robertpin requested changes

2023-01-25 11:34 UTC, robertpin commented on react/features/toolbox/components/web/Toolbox.tsx
> +            overflow: "scroll",
We don't want the menu to scroll all the time. The context menu already has `overflow-y: auto` so this isn't needed

2023-01-25 11:34 UTC, robertpin commented on react/features/toolbox/components/web/Toolbox.tsx
> +            maxHeight: "60vh",
Too small. This would cause the menu to scroll even when there's plenty of space. I think `80vh` should do

2023-01-25 11:42 UTC, robertpin submitted a review, later dismissed

2023-01-25 11:42 UTC, robertpin commented
Jenkins test this please

2023-01-25 11:45 UTC, robertpin commented
Jenkins test this please

2023-01-25 11:47 UTC, robertpin approved these changes

2023-01-25 13:16 UTC, hkirat commented
@robertpin could you elaborate on how/where to do that? Couldn't find a link in `Contributions.md` unless I'm missing something

2023-01-25 13:34 UTC, robertpin commented
> 

@hkirat you don't need to do anything else. Jenkins is the software that manages/ runs our pipelines (including the testing one). We use that comment to tell Jenkins that it should run the tests for this PR, but it seems that I don't have the rights to do it.

2023-01-25 13:34 UTC, robertpin commented
@saghul add Jenkins please

2023-01-25 14:50 UTC, saghul commented
Jenkins please test this please.

2023-01-25 15:24 UTC, robertpin commented
Jenkins test this please

2023-01-25 18:09 UTC, merged