Fixed style of participant badge
jitsi/jitsi-meet pull request #12880
Opened 2023-02-07 20:30 UTC by priyanshu-kun

close issue: https://github.com/jitsi/jitsi-meet/issues/12878

This occurs when the screen width and height become smaller than 368 x 619 or badge number become two or more digits, causing the badge value to overflow the badge container. To address this issue, I made the badge more responsive for larger numbers and smaller devices.

Before: 
![Screenshot from 2023-02-07 23-05-17](https://user-images.githubusercontent.com/57032769/217356396-8171b5bc-886c-40ea-9e3a-b8a09893330d.png)

After fix:
![Screenshot from 2023-02-08 00-13-11](https://user-images.githubusercontent.com/57032769/217356479-fb5cc2a0-da6d-485f-83af-3d8d1fe42008.png)

2023-02-08 05:59 UTC, priyanshu-kun commented
Done, I have signed that.

Individual Name: Priyanshu Sharma
Mailing Address: priyanshusharma507@protonmail.com

2023-02-08 06:27 UTC, saghul commented
@robertpin can you PTAL?

2023-02-08 07:32 UTC, priyanshu-kun commented
> @robertpin can you PTAL?

Sorry, I don't understand can you be more elaborate!

2023-02-08 08:07 UTC, priyanshu-kun commented
@robertpin

2023-02-08 08:45 UTC, robertpin requested changes

2023-02-08 08:45 UTC, robertpin commented on react/features/participants-pane/components/web/ParticipantsCounter.tsx
> +            borderRadius: '12px',
This change isn't necessary

2023-02-08 08:45 UTC, robertpin commented on react/features/participants-pane/components/web/ParticipantsCounter.tsx
> +	    lineHeight: '20px',
Please remove this. The line-height is part of the typography (set in the line above)

2023-02-08 08:45 UTC, robertpin commented on react/features/participants-pane/components/web/ParticipantsCounter.tsx
> +	    textAlign: 'center',
Please indent at the same level as the line above (the line below should also be indented correctly)

2023-02-08 12:01 UTC, priyanshu-kun commented
@robertpin done.

2023-02-09 08:09 UTC, robertpin approved these changes

2023-02-09 08:10 UTC, merged