ref(TS) Improve TS
jitsi/jitsi-meet pull request #13282
Opened 2023-04-27 10:53 UTC by robertpin

Remove unnecessary @ts-ignores
Use @ts-expect-error instead os @ts-ignore for external dependecies

2023-05-02 09:04 UTC, horymury requested changes

2023-05-09 06:39 UTC, robertpin commented on react/features/base/net-info/NetworkInfoService.native.ts
> +    _subscription: NetInfoSubscription | undefined;
Hmm, I was certain that `?:` didn't work in classes but it looks like it does. I'll update it.

2023-05-09 06:41 UTC, robertpin commented on react/features/dropbox/functions.native.ts
> +    const { dropbox = { appKey: undefined } } = state['features/base/config'];
It is implicit in JS. But in TS when we try to use `dropbox.appKey` (below this) we get an error saying `appKey does not exist in type {}`. So I added this to make TS happy

2023-05-09 06:43 UTC, robertpin commented on react/features/filmstrip/actions.native.ts
> +        const rows = Math.ceil(participantCount / columns); // @ts-ignore
The problem is that `StyleSheet` is used in a lot of places. If I change `StyleSheet` we're gonna have a cascade of errors, so I want to treat it separately (have a PR where I change this type and fix all the problems)

2023-05-09 06:44 UTC, robertpin commented on react/features/filmstrip/components/web/Thumbnail.tsx
> +                    width: undefined
Same as https://github.com/jitsi/jitsi-meet/pull/13282#discussion_r1188200379

Only needed to make TS happy

2023-05-09 06:44 UTC, robertpin commented on react/features/filmstrip/functions.native.ts
>      const conferenceBorder = conferenceStyles.conference.borderWidth || 0;
Will do in a separate PR

2023-05-09 07:48 UTC, horymury approved these changes

2023-05-09 08:05 UTC, merged