feat(deeplinking): offer desktop app for download, configurable
jitsi/jitsi-meet pull request #14261
Opened 2024-01-21 21:12 UTC by csett86

Offer the default app, but make it configurable for own branded
desktop clients

Signed-off-by: Christoph Settgast <csett86_git@quicksands.de>

2024-01-22 08:02 UTC, saghul commented
Can you share a screenshot please?

2024-01-22 17:42 UTC, csett86 commented
Yes sure it looks like this:

![Bildschirmfoto 2024-01-22 um 18 40 23](https://github.com/jitsi/jitsi-meet/assets/1392875/8d39498c-32de-42f6-9492-1c8dcd847594)

2024-01-26 08:59 UTC, saghul requested changes
Left come comments!

2024-01-26 08:59 UTC, saghul commented on react/features/base/config/functions.web.ts
> +    if (desktop.download) {
Can you pl simplify this so we don't need to duplicate the URLs? Something like:

```
desktop.download = desktop.download || {};
 desktop.download.windows = desktop.download.windows
            || 'https://github.com/jitsi/jitsi-meet-electron/releases/latest/download/jitsi-meet.exe';
        desktop.download.macos = desktop.download.macos
            || 'https://github.com/jitsi/jitsi-meet-electron/releases/latest/download/jitsi-meet.dmg';
        desktop.download.linux = desktop.download.linux
            || 'https://github.com/jitsi/jitsi-meet-electron/releases/latest/download/jitsi-meet-x86_64.AppImage';
```

2024-01-26 08:59 UTC, saghul commented on react/features/deep-linking/components/DeepLinkingDesktopPage.web.tsx
> +                    <a href = { generateDownloadURL() }>
Could we please put the download link on the same like as "You don't have the app?"

2024-01-26 08:59 UTC, saghul commented on react/features/deep-linking/components/DeepLinkingDesktopPage.web.tsx
> +                        t(`${_TNS}.noMobileApp`)
Let's use a different translation key, in case we ever change the wording to be more mobile specific. `.noDesktopApp` perhaps.

2024-01-26 16:51 UTC, csett86 commented
Thanks a lot for the review and comments, addressed. Now looks better:

![Bildschirmfoto 2024-01-26 um 17 50 37](https://github.com/jitsi/jitsi-meet/assets/1392875/be913331-f29f-41e6-9378-390b0eff7138)

2024-01-26 19:04 UTC, saghul approved these changes

2024-01-26 19:04 UTC, saghul commented
Jenkins please test this please.

2024-01-26 19:05 UTC, saghul commented
Excellent work!

2024-01-26 21:04 UTC, merged