fix(polls): add vertical margin to create poll button (android)
jitsi/jitsi-meet pull request #14537
Opened 2024-03-25 18:17 UTC by nitinkushwaha17

fixes #14536

2024-03-25 18:34 UTC, saghul commented
@Calinteodor PTAL

2024-05-27 15:27 UTC, nitinkushwaha17 commented
@Calinteodor It is a small change. Can you please review this. Thanks.

2024-05-27 15:28 UTC, Calinteodor approved these changes

2024-05-27 15:30 UTC, Calinteodor requested changes

2024-05-27 15:30 UTC, Calinteodor commented on react/features/polls/components/native/styles.ts
> +        marginVertical: BaseTheme.spacing[5]
Can you try and see if using our spacing variables is duable?

2024-05-27 15:31 UTC, merged