feat(polls): web rework
jitsi/jitsi-meet pull request #14645
Opened 2024-04-17 09:31 UTC by Calinteodor

2024-05-17 11:07 UTC, horymury commented on react/features/polls/components/AbstractPollCreate.tsx
> +    answers: Array<string> | any;
would not change the type here

2024-05-17 12:12 UTC, horymury submitted a review, later dismissed

2024-05-17 12:12 UTC, horymury commented on react/features/polls/components/web/PollItem.tsx
> +    setCreateMode: Function;
setCreateMode: (mode: boolean) => void;

2024-05-17 12:12 UTC, horymury commented on react/features/polls/components/web/PollItem.tsx
> +                    // @ts-ignore
could be removed once the Interface def is updated

2024-05-17 12:14 UTC, horymury commented
I would revisit the cases where ts-ignore is used and check whether we can have a way to get rid of it. Also , I would suggest avoiding using `any` for type defs except the cases in which there is no way of knowing it.

2024-05-17 13:07 UTC, Calinteodor commented
> I would revisit the cases where ts-ignore is used and check whether we can have a way to get rid of it. Also , I would suggest avoiding using `any` for type defs except the cases in which there is no way of knowing it.

Thanks Horatiu! I will look into it!

2024-05-20 10:53 UTC, Calinteodor commented on react/features/polls/reducer.ts
> +                    [action]: {
Ops.

2024-05-21 09:23 UTC, horymury requested changes

2024-05-22 09:34 UTC, horymury requested changes

2024-05-22 09:34 UTC, horymury commented on react/features/polls/components/AbstractPollAnswer.tsx
> +const AbstractPollAnswer = (Component: ComponentType<AbstractProps>) => (props: AbstractProps) => {
please revert this - I think the new props (setCreateMode, ...) should go on InputProps type instead  - AbastractProps seem to be defined for the <Component component.

2024-05-22 09:34 UTC, horymury commented on react/features/polls/components/native/PollItem.tsx
> +                // @ts-ignore
please remove once AbstractPollAnswer is fixed

2024-05-22 09:34 UTC, horymury commented on react/features/polls/components/web/PollCreate.tsx
> +
extra space

2024-05-22 09:34 UTC, horymury commented on react/features/polls/components/web/PollItem.tsx
> +                // @ts-ignore
please remove once AbstractPollAnswer is fixed

2024-05-22 10:07 UTC, horymury approved these changes

2024-05-22 10:11 UTC, horymury approved these changes

2024-05-22 10:22 UTC, horymury submitted a review, later dismissed

2024-05-22 10:56 UTC, horymury approved these changes

2024-05-22 12:03 UTC, merged