fit the emoji panel to message tag
jitsi/jitsi-meet pull request #14647
Opened 2024-04-17 14:33 UTC by VirajDilshanKumarage

fit the emoji panel to message tag

![1jitsi](https://github.com/jitsi/jitsi-meet/assets/135811767/ea1e061c-27d4-429d-86c7-a65b9af87cc2)
![2jitsi](https://github.com/jitsi/jitsi-meet/assets/135811767/c87cfa34-a8c6-4941-8f5f-2d527a1dbde5)

if any issue feel free to contact me via email: viraj123e@gmail.com

2024-04-20 05:30 UTC, VirajDilshanKumarage commented
please review this code

2024-04-20 08:25 UTC, saghul requested changes

2024-04-20 08:25 UTC, saghul commented on react/features/chat/components/web/ChatInput.tsx
> +import data from '@emoji-mart/data';
Can you please import this as "emojiData", so it's not so generic?

2024-04-20 08:25 UTC, saghul commented on react/features/chat/components/web/ChatInput.tsx
> +        messages: [],
Unused.

2024-04-20 08:25 UTC, saghul commented on react/features/chat/components/web/ChatInput.tsx
> +
Please avoid newline changes.

2024-04-20 08:25 UTC, saghul commented on react/features/chat/components/web/ChatInput.tsx
> -                                <SmileysPanel
Is this smileys panel used anywhere else now? If not we should delete it.

2024-04-24 11:29 UTC, shawnchin commented on react/features/chat/components/web/ChatInput.tsx
> +                            this._toggleSmileysPanel();}}
Is this correct? Seems strange to toggle on/off the smiley panel each time a message is sent.

2024-08-04 01:58 UTC, closed without merging