fix(chat-features): Add messageId and change id to participantId
jitsi/jitsi-meet pull request #14945
Opened 2024-07-29 05:57 UTC by he-patrick

- messageId needs to be received so that reactions can be attached to specific messages
- participantId indicates that it is the participant's id rather than the message's id

2024-07-30 12:09 UTC, saghul approved these changes
LGTM, we need to land the LJM change first though. @damencho can you PTAL too?

2024-07-31 13:00 UTC, saghul commented
Code looks good, can you please fix the linting errors?

2024-07-31 14:38 UTC, he-patrick commented
Fixed.

2024-07-31 14:50 UTC, he-patrick commented
Let me know if that works 🙂

2024-08-06 08:13 UTC, saghul commented
Unrelated test failure. Landing.

2024-08-06 08:20 UTC, damencho commented
Nope, it is related

2024-08-06 08:20 UTC, damencho commented
IFrameAPICommandsTest. testCommandSendChatMessage

2024-08-06 08:20 UTC, damencho commented
We should figure it out what is the problem as it may break all tests, till now 2 out of 2 are failing.

2024-08-06 09:08 UTC, saghul requested changes

2024-08-06 09:08 UTC, saghul commented on react/features/chat/middleware.ts
> +            participantId,
@he-patrick This is what breaks the external API test. You need to adjust this: https://github.com/jitsi/jitsi-meet/blob/b2e06c1c94803144735c8b8f91e13bd01bc48503/modules/API/API.js#L1348

Please keep "from" there or applications will break.

2024-08-06 12:29 UTC, saghul commented on modules/API/API.js
> -     * @param {string} kicked - The ID of the participant removed from the
This looks like a merge conflict.

2024-08-06 12:47 UTC, saghul commented
Jenkins please test this please.

2024-08-06 13:29 UTC, saghul approved these changes

2024-08-06 13:30 UTC, merged

2024-08-06 13:30 UTC, saghul commented
🚀 🚀 🚀 🚀