create a raisedHands object in config.js
jitsi/jitsi-meet pull request #14975
Opened 2024-08-06 05:08 UTC by liumengyuan1997

Hi reviewer,

This is a GSoC task. I added a raisedHands object in config.js and added its corresponding selectors. Feel free to let me know which part is inappropriate.

Thanks,
Mengyuan

2024-08-06 06:05 UTC, damencho commented on config.js
> -    // disableRemoveRaisedHandOnFocus: false,
You should not delete this, but deprecate it. Check the other options that have DEPRECATED.  in the comment.
You should also make sure that the old config works in parallel with the new one. That ensures that we are not breaking experience for people with the old config set.

2024-08-06 11:02 UTC, saghul requested changes

2024-08-06 11:02 UTC, saghul commented on react/features/base/config/functions.any.ts
> +export function getDisableLowerAllHand(state: IReduxState) {
I think we should use a single option for disabling the lower hand functionality. I'm not sure who would want to allow one but not the other...

2024-08-06 11:02 UTC, saghul commented on react/features/base/participants/subscriber.ts
> -        if (raisedHandsQueue.length && isNextToSpeak(store.getState()) && !hasBeenNotified(store.getState())) {
Why remove the extra check?

2024-08-06 11:02 UTC, saghul commented on react/features/base/config/functions.any.ts
> -    return state['features/base/config']?.disableRemoveRaisedHandOnFocus || false;
The config reducer should allow reading the old value and setting it in the new format.

2024-08-09 09:28 UTC, saghul submitted a review, later dismissed

2024-08-09 09:28 UTC, saghul commented on config.js
> +    //     disableRemoveRaisedHandOnFocus: false
Nit: add a trailing comma so the syntax remains correct even when new options are added after.

2024-08-09 09:29 UTC, saghul commented on config.js
> +    //     disableRemoveRaisedHandOnFocus: false
```suggestion
    //     disableRemoveRaisedHandOnFocus: false,
```

2024-08-09 09:29 UTC, saghul approved these changes

2024-08-09 09:39 UTC, merged