feat(hand-recognition)
jitsi/jitsi-meet pull request #15001
Opened 2024-08-13 05:19 UTC by liumengyuan1997

Hi reviewer,

This is a GSoC task. I added a hand recognition feature by using the Human repository. We should also 'handtrack.json', and 'handlandmark-lite.json' files to the libs folder to use it. Feel free to let me know which part is inappropriate.

Thanks,
Mengyuan

2024-08-15 11:35 UTC, saghul requested changes
Looks really good! Any chance you could upload a video showing it in action?

2024-08-15 11:35 UTC, saghul commented on react/features/face-landmarks/FaceLandmarksDetector.ts
> +                    && messageTimestamp - this.lastRaisedHandTimestamp >= 2000) {
Let's make the value a constant so it can be easily tweaked.

2024-08-15 11:35 UTC, saghul commented on react/features/face-landmarks/FaceLandmarksDetector.ts
> +                } else if (!this.lastRaisedHandTimestamp) {
I think if you test this first and then unconditionally check for the interval it will make the code more readable.

2024-08-15 11:35 UTC, saghul commented on react/features/face-landmarks/FaceLandmarksHelper.ts
> +            skipFrames: 99,
What does this do?

2024-08-15 11:35 UTC, saghul commented on react/features/face-landmarks/FaceLandmarksHelper.ts
> +        return counter > 3 && handLabel === 'hand';
Don't we want to exit early when `handLabel` is something else?

2024-08-15 11:35 UTC, saghul commented on react/features/face-landmarks/FaceLandmarksHelper.ts
> +     * @returns {Promise<[Array<FaceResult>, Array<HandResult>]>}
let's return an object with 2 keys rather an an array of arrays please.

2024-08-15 11:35 UTC, saghul commented on config.js
> +    //     disableRaisedHandRecognition: false,
Extend the comment to mention facial landmarks need to be enabled for this.

2024-08-21 15:15 UTC, liumengyuan1997 commented on react/features/base/config/functions.any.ts
> +    return state['features/base/config']?.raisedHands?.disableRaisedHandRecognition || false;
Boolean(state['features/base/config']?.raisedHands?.disableRaisedHandRecognition)

2024-08-21 15:22 UTC, liumengyuan1997 commented on react/features/face-landmarks/FaceLandmarksHelper.ts
> +        },
delete default.

2024-08-21 15:27 UTC, liumengyuan1997 commented on react/features/face-landmarks/FaceLandmarksHelper.ts
> +                modelPath: 'handtrack.json'
change the make file.

2024-11-22 07:53 UTC, saghul commented
@mihhu shall we land this?

2024-12-06 05:57 UTC, tuhinmallick commented
Any update about this feature ? Zoom has this feature now.

2025-03-19 02:07 UTC, closed without merging