Update german translation
jitsi/jitsi-meet pull request #15011
Opened 2024-08-14 12:22 UTC by fluxxcode

Added all missing translations for German and removed all unused ones using the `update-translation.js` script.

2024-08-14 13:28 UTC, saghul commented
Ping @csett86 :-)

2024-08-14 14:09 UTC, csett86 commented
Will take a look later today, thanks

2024-08-14 19:22 UTC, csett86 requested changes
Thanks a lot for the translation update. I have left suggestions to keep it in sync with the other parts of the German translation

2024-08-14 19:22 UTC, csett86 commented on lang/main-de.json
> +        "viewParticipants": "Teilnehmer anzeigen",
```suggestion
        "viewParticipants": "Personen anzeigen",
```

2024-08-14 19:22 UTC, csett86 commented on lang/main-de.json
> +        "waitingVisitorsTitle": "Das Meeting wurde noch nicht gestartet!",
```suggestion
        "waitingVisitorsTitle": "Die Konferenz wurde noch nicht gestartet!",
```

2024-08-14 19:22 UTC, csett86 commented on lang/main-de.json
> +            "description": "Sie sind derzeit Beobachter dieser Konferenz.",
```suggestion
            "description": "Sie beobachten derzeit diese Konferenz.",
```

2024-08-14 19:22 UTC, csett86 commented on lang/main-de.json
> +            "title": "Dem Meeting wird beigetreten",
```suggestion
            "title": "Konferenz wird beigetreten",
```

2024-08-14 19:22 UTC, csett86 commented on lang/main-de.json
> +            "wishToSpeak": "Wenn Sie sprechen möchten, heben Sie bitte unten Ihre Hand und warten Sie auf die Zustimmung des Moderators"
```suggestion
            "wishToSpeak": "Wenn Sie sprechen möchten, heben Sie bitte unten Ihre Hand und warten Sie auf die Zustimmung der Moderation"
```

2024-08-14 19:22 UTC, csett86 commented on lang/main-de.json
> +        "waitingMessage": "Sie werden dem Meeting beitreten, sobald es live ist!"
```suggestion
        "waitingMessage": "Sie werden der Konferenz beitreten, sobald sie gestartet ist!"
```

2024-08-15 08:41 UTC, fluxxcode commented
@csett86 I have applied and rebased your suggestions. Let me know if there's anything else :)

2024-08-15 09:08 UTC, csett86 approved these changes
Lookgs good, many thanks!

2024-08-15 10:23 UTC, merged

2024-08-15 10:23 UTC, saghul commented
Thanks folks!