Added heart reaction feature
jitsi/jitsi-meet pull request #15291
Opened 2024-11-12 12:59 UTC by KingRain

Closes https://github.com/jitsi/jitsi-meet/issues/15211

Added the heart reaction icon to the Reaction pane and also the necessary audio files for the reaction.

2024-11-12 13:01 UTC, aaronkvanmeerten commented on react/features/reactions/constants.ts
> +    HEART_SOUND_FILES
please add this into the middle to preserve alphabetic sorting.

2024-11-12 13:09 UTC, damencho commented
What is the origin of the sound files?

2024-11-12 13:30 UTC, KingRain commented
> What is the origin of the sound files?

They are from https://uppbeat.io/ made by Epic Stock Media

2024-11-12 13:32 UTC, saghul submitted a review, later dismissed
LGTM! (untested though)

2024-11-12 15:12 UTC, damencho commented
Drop the last commit, it is not relevant to this feature.

2024-11-12 16:13 UTC, aaronkvanmeerten approved these changes
LGTM (also didn't test)

2024-11-12 16:22 UTC, damencho commented
jenkins test this please.

2024-11-13 01:05 UTC, damencho requested changes
This is not looking good, it used to be one line ... 
<img width="519" alt="image" src="https://github.com/user-attachments/assets/9ffbba2e-3fe0-458d-a712-bb632a04eae1">
Also, it is missing the tooltip test: 
<img width="237" alt="image" src="https://github.com/user-attachments/assets/94958c81-278e-46ff-9ccb-b4e32b345442">

Other than that LGTM.

2024-11-13 14:07 UTC, damencho commented
jenkins test this please.

2024-11-13 14:07 UTC, damencho approved these changes

2024-11-13 14:29 UTC, merged

2024-11-13 14:30 UTC, damencho commented
Cheers! Thank you for your contribution.

2024-11-20 22:46 UTC, bgrozev commented
Thanks for the contribution! Please use ~/resources/encode-sound.sh to encode the files next time (to keep the size smaller and formats consistent)