AudioOnlyButton in the overflow menu should be configurable to get a minimalistic ui
jitsi/jitsi-meet pull request #7944
Opened 2020-10-20 14:53 UTC by trippledave

I want to make a very simple UI and the AudioOnlyButton in the overflow menu seems redundant since there is also the VideoMuteButton and i am not allowing screensharing.

So i just made it configurable using the feature flags, implementing it like in the ChatButton

btw. just signed the agreement, do you need ID of the document or what? I´m the guy called David, probably should have written down my github profile name?

2021-02-20 20:22 UTC, trippledave commented
requesting status

2021-02-21 09:24 UTC, saghul requested changes
Sorry this fell through the cracks. One minor nit, LGTM otherwise.

2021-02-21 09:24 UTC, saghul commented on react/features/base/flags/constants.js
> +export const AUDIO_ONLY_BUTTON_ENABLED = 'audio-only.enabled';
Please sort it alphabetically.

2021-02-26 17:48 UTC, trippledave reviewed
sorted and then fixed merge isssues in
https://github.com/jitsi/jitsi-meet/pull/7944/commits/cbae174bcb6f0101750a4c4ed87cd2c3061b10dc

not sure why it display the lines 9-14 as new, since they where there before but what do i know

2021-03-19 07:17 UTC, saghul approved these changes

2021-03-19 07:17 UTC, merged

2021-03-19 07:17 UTC, saghul commented
Cheers!