fix(vpaas): Store billing id in parent lolcaStorage on Safari
jitsi/jitsi-meet pull request #8401
Opened 2021-01-13 10:22 UTC by vp8x8

Safari browser does not persist data between sessions for iframes hosted on a
different domain. In this case a mechanism of storing the billingId on the
parent localStorage was added.

2021-01-14 07:34 UTC, vp8x8 commented
Jenkins, test this please.

2021-01-14 07:39 UTC, vp8x8 commented
Jenkins, test this please.

2021-01-14 23:11 UTC, hristoterezov commented on modules/API/API.js
> +            commands['transfer-billing-id'] = function(id) {
Actually this mechanism is already implemented in the Transport class. Check https://github.com/jitsi/js-utils/blob/master/transport/Transport.js#L225. We already use this in external_api.js for example in the invite method. Maybe you can use it here as well?

2021-01-14 23:28 UTC, hristoterezov requested changes
I left a small suggestion.

Do I understand correctly that the whole localStorage won't work in this case?

We save a bunch of values there for the devices, display name, the prejoin screen. Does that mean that those value won't be persisted too? Wouldn't we want to fix those as well?

Also what exactly is happening in this case. The localStorage is not available at all or it is available but it is cleared when you reload?

We are actually already doing something similar when we detect that the local storage is not supported. But we actually store the whole localStorage object on the host page. We send to the JitsiMeetExternalAPI object the local storage content and we are updating it when it changes. JitsiMeetExternalAPI will store it using the host page localStorage and on the next session when the URL for the iframe is constructed the whole localStorage is passed there. This is the commit that introduced it https://github.com/jitsi/jitsi-meet/commit/dc6d3daef73b2eda6121feb2728e0796f65aa545 . We try to auto detect this situation and enable the scheme for using the local storage on the host page. Maybe you need to only extend the check to cover the Safari use case and the whole local storage will just work without any other changes needed. WDYT?

2021-01-15 12:52 UTC, vp8x8 commented
Thanks for the suggestion! I missed the fact that the functionality was already there. I piggybacked on it.

In Safari, localStorage is available and functional, but it's cleared between sessions. This is happening only for iframes hosted on a different domain than the parent. Apparently is something that Apple does to prevent data leaking.

2021-01-15 23:29 UTC, hristoterezov approved these changes
Awesome! Thanks!

2021-01-18 07:56 UTC, merged