add option for disabling join/leave sounds
jitsi/jitsi-meet pull request #8596
Opened 2021-02-10 01:12 UTC by adqm

This PR adds an option `disableJoinLeaveSounds` to `config.py`, which can be set to `true` to disable the join/leave sounds (which I and my students found distracting in a large class meeting).  

I couldn't find a way to turn off the sounds with the current configuration options, short of replacing the WAV files with silence.  But if this kind of option already exists, or if there is a cleaner way to do this, I'd be interested to know :)

2021-02-10 08:36 UTC, saghul requested changes

2021-02-10 08:36 UTC, saghul commented on config.js
> +     disableJoinLeaveSounds
Please document it.

2021-02-10 08:36 UTC, saghul commented on react/features/base/participants/middleware.js
> +    // if we have sounds disabled, don't play anything.
Punctuation: start with a capital letter.

2021-02-10 08:36 UTC, saghul commented on config.js
> +     disableJoinLeaveSounds
Also, add it to the whitelist please.

2021-02-10 17:25 UTC, adqm commented
Thanks @saghul!  I just pushed some changes based on your feedback.

2021-03-22 10:20 UTC, saghul commented
Jenkins please test this please.

2021-03-22 10:20 UTC, saghul approved these changes

2021-03-22 16:28 UTC, merged