Update main-da.json
jitsi/jitsi-meet pull request #8642
Opened 2021-02-18 13:27 UTC by palle64

Improved the Danish translation of Jitsi

2021-02-18 13:32 UTC, palle64 commented
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

I have done that now :-)

2021-02-24 18:00 UTC, jokjr requested changes
I have some suggestions :)

2021-02-25 07:12 UTC, palle64 commented on lang/main-da.json
>          "dialInSummaryError": "Der er opstået en fejl under hentning af ring ind information. Forsøg venligst igen senere.",
Jeg var også med i tvivl ang. denne oversættelse, men jeg synes dit forslag er godt, så det retter jeg det lige til.

2021-02-26 08:39 UTC, jokjr approved these changes

2021-03-03 14:11 UTC, damencho commented
Jenkins, test this please.

2021-03-03 20:44 UTC, damencho approved these changes

2021-03-03 20:44 UTC, merged