fix(blur-effect) enable blur effect for non simd and check ctx filter…
jitsi/jitsi-meet pull request #8679
Opened 2021-02-24 15:47 UTC by tudor-phd

… support.

2021-02-24 16:14 UTC, damencho commented
Maybe we can remove and the beta label :) @saghul WDYT?

2021-02-24 16:22 UTC, tudor-phd commented
> Maybe we can remove and the beta label :) @saghul WDYT?

I already removed the beta label.

2021-02-24 16:24 UTC, damencho commented
> > Maybe we can remove and the beta label :) @saghul WDYT?
> 
> I already removed the beta label.

Sorry and thank you 👏

2021-02-24 17:16 UTC, saghul requested changes
Left some comments, PTAL!

2021-02-24 17:16 UTC, saghul commented on react/features/blur/functions.js
> +    if (ctx.filter === 'undefined') {
This doesn't work, it's comparing the string value. You need to either check with `typeof` or test directly `undefined` (no quotes).

2021-02-24 17:16 UTC, saghul commented on react/features/blur/functions.js
> +    if (ctx.filter === 'undefined') {
Also, let's stop the value of the test in a variable outside the function so we don't need to recompute it with every call to this function.

2021-02-24 17:16 UTC, saghul commented on react/features/blur/functions.js
> +    canvas.remove();
This line probably never runs with the current code.

2021-02-24 17:16 UTC, saghul commented on react/features/stream-effects/blur/JitsiStreamBlurEffect.js
> +    constructor(bpModel: Object, dimensionOptions: Object) {
Let's call it `options`, since we might add more things than dimension, such as the blur factor, later on.

2021-02-24 17:16 UTC, saghul commented on react/features/stream-effects/blur/JitsiStreamBlurEffect.js
> +        this.segmentationPixelCount = this._options.segmentationWidth * this._options.segmentationHeight;
Make this `_segmentationPixelCount`

2021-02-24 17:16 UTC, saghul commented on react/features/stream-effects/blur/index.js
> +        'segmentationHeight': 96,
no need for the prefix, let's call these height and width.

2021-02-24 17:16 UTC, saghul commented on react/features/stream-effects/blur/index.js
> +    'version96': {
on the other object we use the numbers directly as the keys, let's pick one and be consistent. Let's say `modelXX`

2021-02-24 17:16 UTC, saghul commented on react/features/toolbox/components/web/Toolbox.js
> +import { checkFilterSupport } from '../../../blur/functions';
Let's give this a more specific name. A filter could potentially be anything. `checkBlurSupport`.

2021-02-25 12:08 UTC, saghul commented on react/features/stream-effects/blur/JitsiStreamBlurEffect.js
> +     _segmentationPixelCount: number;
```suggestion
    _segmentationPixelCount: number;
```

2021-02-25 12:09 UTC, saghul approved these changes
Looking good, nice work Tudor!

2021-02-25 12:21 UTC, merged