feat:(tile-view) Config for allowing tileview for single participant
jitsi/jitsi-meet pull request #8861
Opened 2021-03-23 12:40 UTC by horymury

Added config for enabling tile view button and mode even for a lonely meeting.

@saghul

2021-03-23 14:05 UTC, damencho approved these changes

2021-03-24 10:09 UTC, saghul commented
Please don't merge this yet. I'd like us to discuss introducing a more flexible model. Here is the gist of it:

* A config option called `layoutMode`, which can be `auto`, `stage-view` or `tile-view`.
* Another config option called `autoTileViewThreshold` which is the amount of participants necessary to go into tile view when in auto mode. Before the threshold is met stage view will be used.
* (Maybe) a `recordingLayoutMode` in case we want the recording to follow a specific mode by default.

What you need would be accomplished by setting `layoutMode` to `auto` and `autoTileViewThreshold` to `1`.

2021-03-24 10:09 UTC, saghul requested changes
Please read my general observation comment.

2021-04-08 11:44 UTC, closed without merging

2021-04-08 11:45 UTC, horymury commented
Closing as discussed. This became redunant since @saghul  already enabled tileview button on single participant.