feat(Labels): Redesign labels on mobile & web
jitsi/jitsi-meet pull request #8936
Opened 2021-04-02 11:15 UTC by vp8x8

![header](https://user-images.githubusercontent.com/37841821/113411110-a1f19c00-93bd-11eb-8aba-2e609819c1cb.png)
![Simulator Screen Shot - iPhone 12 mini - 2021-04-02 at 14 10 54](https://user-images.githubusercontent.com/37841821/113411119-a61db980-93bd-11eb-97e6-cfc5b5fde8ef.png)

2021-04-06 14:03 UTC, saghul requested changes
Left some comments, PTAL.

2021-04-06 14:05 UTC, saghul commented
<img width="670" alt="Screenshot 2021-04-06 at 16 00 18" src="https://user-images.githubusercontent.com/317464/113723535-bc938000-96f1-11eb-94a0-5bd16f89e55d.png">

We need the text to be elided when too long.

2021-04-08 08:37 UTC, vp8x8 commented on ios/Podfile.lock
> +  react-native-background-timer: 029c606b3fd6dd476b153e177c518b6ade4c169f
Removed.

2021-04-08 08:37 UTC, vp8x8 commented on react/features/conference/components/web/Labels.js
> +        _showVideoQualityLabel: !(shouldDisplayTileView(state) || interfaceConfig.VIDEO_QUALITY_LABEL_DISABLED)
Done.

2021-04-08 09:44 UTC, saghul commented on react/features/conference/components/web/Labels.js
> +        _showVideoQualityLabel: !(shouldDisplayTileView(state) || interfaceConfig.VIDEO_QUALITY_LABEL_DISABLED)
Wonderful!

2021-04-08 09:57 UTC, saghul approved these changes
Excellent work Vlad! 👏

2021-04-08 09:57 UTC, merged