Feature/android toggle camera improvement
jitsi/jitsi-meet pull request #9083
Opened 2021-04-24 06:05 UTC by himanshut0305

Added Camera toggle feature for android in broadcast event, added proper intent builder for the same in android SDK,
this gives an additional control to the integrator to manage the camera facing mode with the help of event emitted.

2021-04-28 07:54 UTC, saghul requested changes

2021-04-28 07:54 UTC, saghul commented on android/app/build.gradle
> +
Unnecessary change, please undo it.

2021-04-28 07:54 UTC, saghul commented on android/app/src/main/java/org/jitsi/meet/MainActivity.java
> +
ditto

2021-04-28 07:54 UTC, saghul commented on android/app/src/main/java/org/jitsi/meet/MainActivity.java
> +        Log.d(this.getClass().getSimpleName(), "LIBRE_BUILD="+ BuildConfig.LIBRE_BUILD);
ditto

2021-04-28 07:54 UTC, saghul commented on android/app/src/main/java/org/jitsi/meet/MainActivity.java
> +                    // Otherwise use default URL from app-restrictions.xml.
ditto

2021-04-28 07:54 UTC, saghul commented on android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastIntentHelper.java
> +    public static Intent buildToggleCameraIntent() {
please leave an empty line between functions

2021-04-28 07:54 UTC, saghul commented on android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastIntentHelper.java
> +        Intent intent = new Intent(BroadcastAction.Type.TOGGLE_CAMERA_FACING_MODE.getAction());
No need to create a variable just for returning it immediately

2021-04-28 07:54 UTC, saghul commented on react/features/mobile/external-api/middleware.js
> +// ,TOGGLE_CAMERA_FACING_MODE
?

2021-04-28 07:54 UTC, saghul commented on react/features/mobile/external-api/middleware.js
> +    /*Added listner for event toggle camera for android*/
drop the comment

2021-04-28 07:54 UTC, saghul commented
I'd like to see this implemented for iOS.

2021-04-28 21:17 UTC, himanshut0305 commented on android/app/build.gradle
> +
done, thanks for assist!

2021-04-28 21:18 UTC, himanshut0305 commented on android/app/src/main/java/org/jitsi/meet/MainActivity.java
> +
ditto

2021-04-28 21:20 UTC, himanshut0305 reviewed
made all the changes requested.

2021-04-28 21:20 UTC, himanshut0305 commented on android/sdk/src/main/java/org/jitsi/meet/sdk/BroadcastIntentHelper.java
> +    public static Intent buildToggleCameraIntent() {
done!

2021-05-11 06:13 UTC, vp8x8 commented on package.json
> +    "jQuery-Impromptu": "github:trentrichardson/jQuery-Impromptu#v6.0.0",
We don't use this addon anymore.

2022-04-17 05:32 UTC, closed without merging