dependency(react-native-paper) added react-native-paper dep, updated babel and added optional require dep for react-native-icons
jitsi/jitsi-meet pull request #9134
Opened 2021-05-04 09:32 UTC by Calinteodor

2021-05-04 12:55 UTC, saghul requested changes
Left a couple of comments, PTAL. Mostly, let's start providing stuff in base/ui, like web. Also, screenshot please? :-)

2021-05-04 12:55 UTC, saghul commented on react/features/settings/components/native/SettingsView.js
> +import { DefaultTheme, Divider, Provider as PaperProvider, Switch, TextInput } from 'react-native-paper';
Now that we have base/ui, let's have a JitsiThemeProvider there, like web does.

2021-05-04 12:55 UTC, saghul commented on react/features/settings/components/native/SettingsView.js
> +const theme = {
Let's have a theme built from the tokens, like web does in base/ui

2021-05-04 12:55 UTC, saghul commented on react/features/settings/components/native/styles.js
> +    textInputBorderColor: ColorPalette.blueHighlight,
Shouldn't this be part of the theme?

2021-05-04 12:55 UTC, saghul commented
Also check the tests please.

2021-05-06 14:07 UTC, saghul commented
Jenkins please test this please.

2021-05-07 11:21 UTC, Calinteodor commented
![Android Expanded](https://user-images.githubusercontent.com/26413496/117442473-7a9f6900-af3f-11eb-8ebf-6feda6110d0c.png)
![IOS Expanded](https://user-images.githubusercontent.com/26413496/117442480-7c692c80-af3f-11eb-910a-28bdd4634e79.png)
![Android](https://user-images.githubusercontent.com/26413496/117442483-7d01c300-af3f-11eb-8ddb-874c42383834.png)
![IOS](https://user-images.githubusercontent.com/26413496/117442484-7d01c300-af3f-11eb-951f-dfd4ef29ccf9.png)

2021-05-07 11:24 UTC, saghul submitted a review, later dismissed
LGTM! Can you please attach a screenshot?

2021-05-07 13:26 UTC, saghul commented
FTR: for some odd reason the bundle size increases the CIs see are not reproducible on macOS. We are investigating.

2021-05-07 22:20 UTC, saghul commented
@Calinteodor Upon testing, the text seems cut at the top when typing on the textfields (Android). PTAL.

2021-05-08 08:01 UTC, saghul commented
Also, I think the arrows on the accordion are reversed, aren't they? I think it should point downwards when it needs expanding, and upwards when it will collapse.

2021-05-10 13:13 UTC, Calinteodor commented
> @Calinteodor Upon testing, the text seems cut at the top when typing on the textfields (Android). PTAL.

2021-05-10 13:15 UTC, Calinteodor commented
> > @Calinteodor Upon testing, the text seems cut at the top when typing on the textfields (Android). PTAL.

Can u send me a screenshot please? I tested on master, to see how the text looks inside the old textfields and I didn't see any difference.

2021-05-10 13:17 UTC, Calinteodor commented
> Also, I think the arrows on the accordion are reversed, aren't they? I think it should point downwards when it needs expanding, and upwards when it will collapse.

Fixed

2021-05-11 08:01 UTC, saghul approved these changes

2021-05-11 08:01 UTC, merged

2021-05-11 08:01 UTC, saghul commented
I was testing with a too large font, nevermind!