feat(thumbnails) Add changes to mobile context menu
jitsi/jitsi-meet pull request #9480
Opened 2021-06-30 16:12 UTC by horymury

- long touch on thumbnail opens context menu
- hide context menu icon
- add button for connection info to context menu

2021-06-30 18:20 UTC, horymury commented
Jenkins test this please

2021-07-02 12:33 UTC, vp8x8 commented
I think the button should be moved above the volume slider. It looks a bit weird right now.
![Screenshot 2021-07-02 at 15 12 09](https://user-images.githubusercontent.com/37841821/124275188-d60a6380-db4a-11eb-8d11-644aa8b339a1.png)

2021-07-02 12:33 UTC, vp8x8 requested changes

2021-07-02 12:33 UTC, vp8x8 commented on react/features/base/connection/reducer.js
> +            return {
There should be a check here in case the new action is the same as the old one so we don't trigger a useless re-render.

2021-07-05 12:01 UTC, horymury commented on react/features/video-menu/components/web/ConnectionInfoPane.js
> +};
done. passing a `padded` bool value which decides the className.

2021-07-05 12:02 UTC, horymury commented on react/features/connection-indicator/components/web/ConnectionIndicatorContent.js
> +        = typeof participantId === 'undefined' ? getLocalParticipant(state) : getParticipantById(state, participantId);
fixed

2021-07-05 12:02 UTC, horymury commented on react/features/filmstrip/components/web/Thumbnail.js
> +     * Refference to local or remote Video Menu trigger button instance.
fixed

2021-07-05 12:02 UTC, horymury commented on react/features/video-menu/actions.web.js
> + * @returns {Function}
oops

2021-07-05 12:03 UTC, horymury commented
> I think the button should be moved above the volume slider. It looks a bit weird right now.
> ![Screenshot 2021-07-02 at 15 12 09](https://user-images.githubusercontent.com/37841821/124275188-d60a6380-db4a-11eb-8d11-644aa8b339a1.png)

correct, fixed

2021-07-05 12:57 UTC, horymury commented
Jenkins test this please

2021-07-06 06:45 UTC, vp8x8 commented
Jenkins please test this please.

2021-07-06 07:01 UTC, vp8x8 commented
I see there is a scroll now. Other that that this looks good.
![Screenshot 2021-07-06 at 10 00 28](https://user-images.githubusercontent.com/37841821/124556576-1c104180-de41-11eb-988c-639387727215.png)

2021-07-06 11:18 UTC, vp8x8 submitted a review, later dismissed

2021-07-06 12:34 UTC, muscat1 approved these changes

2021-07-06 13:07 UTC, horymury commented
Jenkins please test this please.

2021-07-06 13:29 UTC, horymury commented
Jenkins please test this please.

2021-07-06 13:46 UTC, merged