Additional configuration to customize streaming dialog
jitsi/jitsi-meet pull request #9539
Opened 2021-07-13 22:31 UTC by skolmer

The current streaming feature already allows us to stream to other streaming providers than youtube by submitting a rtmp-url instead of a youtube stream key. This is great but there is currently no way to change the UI to include details about the streaming service we want to use.
We extended the dialog with config parameters that allow us to change the default terms and condition link, the privacy policy link and also the regex that is used to validate the input. 
The help link was already part of the interface config so we added the new params accordingly.
This PR will fix  #9524

2021-08-17 19:31 UTC, skolmer commented
@saghul To support your current effort in deprecating the `interface_config.js`, should we move this to `config.js` including the already existing `LIVE_STREAMING_HELP_LINK`? Any preferences how this should be structured? Multiple config values or one config object that contains everything `liveStreaming` related?

2021-08-18 07:26 UTC, saghul commented
> To support your current effort in deprecating the `interface_config.js`, should we move this to `config.js` including the already existing `LIVE_STREAMING_HELP_LINK`?

THANK YOU! Much appreciated. Yes, let's do that.



> Any preferences how this should be structured? Multiple config values or one config object that contains everything `liveStreaming` related?

The latter, a `liveStreaming` object which contains everything.

Now, that would break backwards compatibility, so you can add a small "translation" piece of code here: https://github.com/jitsi/jitsi-meet/blob/fbf9d489f0103c97e6260aae9ce721592b3e8ea6/react/features/base/config/reducer.js#L189 like we do for `toolbarButtons`.

Thanks for doing this!

2022-01-11 18:44 UTC, skolmer commented
@saghul I see there are some conflicts and the bot marked it as `wontfix`. Is this PR obsolete now or are there still plans to merge it. If so please let us know and we try to fix the conflicts.

2022-01-12 16:13 UTC, saghul commented
Sure thing, we'd love to have it. Sorry it fell through the cracks, can you please rebase it and fix the conflicts?

2022-01-13 17:38 UTC, skolmer commented
> Sure thing, we'd love to have it. Sorry it fell through the cracks, can you please rebase it and fix the conflicts?

Perfect, we just fixed the merge conflict so the PR is now ready again to be merged.

2022-01-27 11:26 UTC, skolmer commented
@saghul Can you give us a note when the right time is to get this merged? We can than fix merge conflicts on short notice. Otherwise we will do it over and over again 😉

2022-01-27 13:21 UTC, saghul commented
Sorry for the delay. I am planning to spend time on this PR tomorrow.

2022-01-28 08:48 UTC, saghul requested changes
Left some comments, PTAL.

2022-01-28 08:48 UTC, saghul commented on config.js
> +    liveStreaming: {
Please make the whole object here optional, aka, leave it commented out. It makes canging defaults much easier in the long run.

2022-01-28 08:48 UTC, saghul commented on react/features/base/config/reducer.js
> +    // Migrate interfaceConfig.LIVE_STREAMING_HELP_LINK
This will need to make sure the new object exists, since it may be undefined.

2022-01-28 08:48 UTC, saghul commented on react/features/recording/components/LiveStream/AbstractStreamKeyForm.js
> +        const liveStreaming = this.props._liveStreaming || {};
Usually we provide default values in `mapStateToProps`

2022-01-28 08:48 UTC, saghul commented on react/features/recording/components/LiveStream/AbstractStreamKeyForm.js
>  const LIVE_STREAMING_HELP_LINK = 'https://jitsi.org/live';
Maybe this can go in `./constants` as well?

2022-01-28 08:48 UTC, saghul commented on react/features/recording/components/LiveStream/native/StreamKeyForm.js
> +export default translate(connect(_mapStateToProps)(StreamKeyForm));
Doesn't this break anything? We were taking abstract props from base/dialog.

2022-05-23 11:53 UTC, skolmer commented
Hi @saghul could you take another look at this PR it looks like it is now ready to be merged?

2022-05-23 20:02 UTC, saghul commented
Thanks for the poke. I'll be afk until next week, I'll take a look when I'm back.

2022-06-13 08:36 UTC, skolmer commented
> Thanks for the poke. I'll be afk until next week, I'll take a look when I'm back.

Just a friendly reminder 😊

2022-06-13 12:48 UTC, saghul requested changes
Left some comments, PTAL!

2022-06-13 12:48 UTC, saghul commented on react/features/recording/components/LiveStream/AbstractStreamKeyForm.js
> +export function _getLiveStreaming(state: Object) {
Make function called `getLiveStreaming` in functions.any.js actually do this and give you the nice pre-filled object.

2022-06-28 13:49 UTC, skolmer commented
> Left some comments, PTAL!

Hey, sorry for the late response. We made the suggested changes. If you agree with them we should be ready to merge :)

2022-07-04 14:02 UTC, saghul commented on react/features/base/config/reducer.js
> +    // Migrate interfaceConfig.LIVE_STREAMING_HELP_LINK
When you move the enabled option, please add migration code here.

2022-07-04 14:04 UTC, saghul commented on react/features/recording/components/LiveStream/functions.js
> +// @flow
Drop the flow anotation please, we are migrating to TS.

2022-07-04 14:05 UTC, saghul commented on react/features/recording/components/LiveStream/index.js
> +export * from './functions';
Don't export anything from a feature's index.js, just use the full path to /functions when importing from another feature.

2022-07-20 15:05 UTC, saghul commented
webpack chokes on something so I cannot test it. Can you please make sure the linter is tamed? Apologies in advance because this is in part our fault due to the transition to TypeScript.

2022-07-20 17:44 UTC, skolmer commented
> webpack chokes on something so I cannot test it. Can you please make sure the linter is tamed? Apologies in advance because this is in part our fault due to the transition to TypeScript.

No worries, it should work now :)

2022-07-21 13:33 UTC, saghul commented
You can run `npm lint` locally to be sure, since I seem to need to approve every GH action run :-/

2022-07-21 13:37 UTC, skolmer commented
@segnord Can you take a look? There still seems to be an issue with the Config type:

>  Error: react/features/base/config/reducer.ts(423,14): error TS2339: Property 'liveStreaming' does not exist on type 'IConfig'.
Error: react/features/base/config/reducer.ts(423,39): error TS2339: Property 'liveStreaming' does not exist on type 'IConfig'.
Error: react/features/base/config/reducer.ts(427,18): error TS2339: Property 'liveStreaming' does not exist on type 'IConfig'.
Error: react/features/base/config/reducer.ts(428,25): error TS2339: Property 'liveStreaming' does not exist on type 'IConfig'.
Error: react/features/base/config/reducer.ts(434,18): error TS2339: Property 'liveStreaming' does not exist on type 'IConfig'.
Error: react/features/base/config/reducer.ts(437,18): error TS2339: Property 'liveStreaming' does not exist on type 'IConfig'.
Error: react/features/base/config/reducer.ts(438,25): error TS2339: Property 'liveStreaming' does not exist on type 'IConfig'.
Error: Process completed with exit code 2.

2022-07-21 15:20 UTC, segnord commented
@skolmer Sorry, I didn't notice that the linter in the main branch now scans typescript files, I've merged the master branch into this MR and the npm lint runs fine locally.

2022-08-02 08:14 UTC, skolmer commented
@saghul The pipeline is now green, can you take another look if everything is fine now?

2022-08-02 08:26 UTC, saghul approved these changes

2022-08-02 08:27 UTC, merged

2022-08-02 08:27 UTC, saghul commented
Cheers!