feat(disable-gsm-bars): Add parameter to disable gsm bars.
jitsi/jitsi-meet pull request #9887
Opened 2021-09-08 08:17 UTC by tudor-phd

2021-09-08 15:11 UTC, saghul requested changes
Left some ccomments, PTAL.

2021-09-08 15:11 UTC, saghul commented on react/features/connection-indicator/components/AbstractConnectionIndicator.js
> + *     _autoHideTimeout: number
just say `{Props}` here.

2021-09-08 15:11 UTC, saghul commented on react/features/connection-indicator/components/AbstractConnectionIndicator.js
> +
please remove the unneeded newline

2021-09-08 15:11 UTC, saghul commented on react/features/filmstrip/components/web/Thumbnail.js
> +        || Boolean(state['features/base/config'].connectionIndicators?.disabled),
can you indent this one more level to make it easier to read?

2021-09-08 15:11 UTC, saghul commented on react/features/base/config/reducer.js
> +        || interfaceConfig.CONNECTION_INDICATOR_AUTO_HIDE_ENABLED
I think we need to checck for these differently sine they are boolean. We need to check if the object contains those properties, not their values.

2021-09-08 15:11 UTC, saghul commented on react/features/base/config/reducer.js
> +    && typeof interfaceConfig === 'object' && (interfaceConfig.CONNECTION_INDICATOR_DISABLED
please indent this one more level

2021-09-08 15:11 UTC, saghul commented on config.js
> +    // connectionIndicators: {
Please remove the legacy options from interface_config.js . Just leave a comment saying they got moved to config.js.

2021-09-08 18:16 UTC, saghul requested changes

2021-09-08 18:16 UTC, saghul commented on interface_config.js
> +    // Connection indicators got moved to config.js
Please keep the names of the options listed, so when one greps for them you can see them there.

2021-09-08 18:16 UTC, saghul commented on react/features/connection-indicator/components/web/ConnectionIndicator.js
> +            && !this.props._connectionIndicatorInactiveDisabled) {
Is this the right place to do this? IIRC there is another place which checks if an icon has to be rendered at all. Can you check?

2021-09-09 10:55 UTC, saghul commented on interface_config.js
> +    // Connection indicators (CONNECTION_INDICATOR_AUTO_HIDE_ENABLED, CONNECTION_INDICATOR_AUTO_HIDE_TIMEOUT, CONNECTION_INDICATOR_DISABLED) got moved to config.js.
Please list them vertically to avoid having such a long line.

2021-09-09 10:58 UTC, saghul reviewed
LGTM with a nit.

2021-09-09 12:47 UTC, saghul approved these changes

2021-09-09 12:50 UTC, merged

2021-09-19 05:44 UTC, Mohamed-Gibreel commented
Is this working on mobile ? I cannot seem to get any indicator on mobile, how do I enable it ?

2021-09-19 07:13 UTC, saghul commented
Not all indicators are available on mobile. It follows a different logic.